### ISSUE TITLE
Mic icon not showing on RecordButton

### ISSUE THREAD

**Issue by fifisamy** [3llomi/RecordView#1]
Mic Icon Not Appear on RecordButton

**Comment by 3llomi** [comment]
could you please give me more info ?
what android version you are using? .
 is the icon a Vector Drawable?.
and please make sure you are using the `app ` namespace instead of `android` in XML

**Comment by munirbraganca** [comment]
I´m having the same problem in android 5.0.1
Using Vector Drawable but the icon doesnt appear, only the background appear.

**Comment by munirbraganca** [comment]
Fixed using android:src="VectorDrawable" instead of app:src="VectorDrawable"

**Comment by 3llomi** [comment]
@munirbraganca you should **NOT** use the `android:src` for the `RecordButton` because it may crash on older APIs .
anyway an update has been pushed and hopefully the bug was fixed.

please re open this issue if the problem still exists

**Comment by fifisamy** [comment]
it worked on android 6 .. android 4  have this problem
but i solved it by create my own mic drawable

**Comment by 3llomi** [comment]
@fifisamy hmm, i already tested it on **API 17** and it's working.
did you try the vector drawable that bundled with the Library?, `ic_mic_white`

**Comment by fifisamy** [comment]
Yes but with some devices like samsung note 3  problem happened

**Comment by 3llomi** [comment]
it should be fixed with `V2.0.0`
