### ISSUE TITLE
Got error when implementation 'com.devlomi.record-view:record-view:2.0.0' 

### ISSUE THREAD

**Issue by juniorfrogie** [3llomi/RecordView#21]
I got this error when sync gradle:

Program type already present: android.arch.lifecycle.ViewModel
Message{kind=ERROR, text=Program type already present: android.arch.lifecycle.ViewModel, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by Khusinov** [comment]
I have some problems with this library. I implemented this version:   implementation ("com.devlomi.record-view:record-view:2.0.1")


But in XML file, when I try to write <com.devlomi or when I paste recordView's XML code, nothing importing. 
what should I do ?
