### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [3llomi/RecordView#23]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by 3llomi** [comment]
Hey @mansya.
Of course , that would be awesome.
Waiting for your Cool design.
Thanks for your effort.

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ? or is there a color change ?
![record view](https://user-images.githubusercontent.com/33461607/44405818-5f6c4f80-a584-11e8-91f7-d280d9cc3da4.png)

**Comment by 3llomi** [comment]
Thanks @mansya ,it's awesome. i would go with Icon 11

**Comment by 3llomi** [comment]
merged, Thanks for your efforts .
