### ISSUE TITLE
Recording lock option

### ISSUE THREAD

**Issue by sepehr1014** [3llomi/RecordView#24]
Thank you for this great project. Are there any plans to add locking behavior? Something Telegram messenger has had for many years and WhatsApp has added recently:

https://www.androidpolice.com/2018/04/05/whatsapp-2-18-102-brings-voice-note-recording-lock-option/

**Comment by 3llomi** [comment]
Hi @sepehr1014 ,
Yes i have this idea in my mind, it's just needs some time to make it work.

**Comment by Tougee** [comment]
@sepehr1014  
[You can check this project same as Telegram](https://github.com/Tougee/AudioRecorderView)

**Comment by 3llomi** [comment]
@Tougee Good Job man it's Great.
it would be awesome to add Lock feature to 'Record View'  :wink:

**Comment by Mustafa-Altameemi** [comment]
> Hi @sepehr1014 ,
> Yes i have this idea in my mind, it's just needs some time to make it work.

Thanks for your library. I'm wondering if you have done the recording lock by now or not?

**Comment by 3llomi** [comment]
@Mustafa-Altameemi Not yet. not sure if i can add this in the near future.

**Comment by 3llomi** [comment]
if anyone is interested, i've added this feature in a separate branch since it's in Beta.

implementation 'com.github.3llomi:RecordView:record-lock-ee919e1d70-1'

looking forward for your feedback.

**Comment by waqaruet** [comment]
any update on beta version of lock option? I see a lot of bugs and incomplete functionality in Lock mode. Please inform what's the plan to take it out of beta?

**Comment by waqaruet** [comment]
1. When we hold mike in Lock mode enabled, mike position changes from its base position which looks awkward
2. If user enters the lock mode and then get into onPause, onStop state then their is no handling listener or way to take it out of lock mode programatically or it should automatically stop.
3. Lock animation should be customiseable.

**Comment by 3llomi** [comment]
Hey @waqaruet ,
Unfortunately I don't have enough time for this, I will try my best to finish it ASAP.

Thanks for your notes though, I just wanted to know that you are using the latest beta `V3.1.0beta6` ? 

1.  The current implementation works ONLY if `RecordLock` AND `RecordButton` are in different parents.  i need to handle the case where both have the same parent.

2. Yes, I am thinking of adding something like `recordView.finishRecord()` so we can call it inside `onPause()` for example to Finish the record

3. let me know your thoughts about how can we make it customizable.

**Comment by waqaruet** [comment]
@3llomi  Thanks for your response, appreciate that,
I'm using V3.1.0beta6
1. Yes, RecordLock AND RecordButton are in different parents.
2. recordView.finishRecord() and recordView.cancelRecord() would be really handfull
3. Customization like to make similar to whatsapp i.e Shimmer text, shimmer text color , background color , lock Icon , lock animation on/off. unlock icon

**Comment by 3llomi** [comment]
Thanks for your feedback!.

1. can you reproduce it? like posting a Video sample?

**Comment by waqaruet** [comment]
Yes, I can re-produce it, attaching video as well.
You can see record button changes its position on touch

https://user-images.githubusercontent.com/41164853/133897539-259e45d8-d3a1-44d5-988a-a9530de1b21b.mp4

.

**Comment by 3llomi** [comment]
@waqaruet Thanks for the Video! 
I will try to fix it ASAP.

**Comment by 3llomi** [comment]
now it's fully working with V3.1.1 🎉🎉

**Comment by Mahesh160393** [comment]
@3llomi How to change the lock icon image?

**Comment by 3llomi** [comment]
@Mahesh160393 You can't. 
I used two images for the Lock Icon, so if you tried to change both images it may result in incorrect behavior since the Lock size may differ.
