### ISSUE TITLE
Record Cancelled when clicking the Record Button

### ISSUE THREAD

**Issue by PemmasaniRajesh** [3llomi/RecordView#3]
I'm using this record button in card view which is in center of my layout.
`<android.support.v7.widget.CardView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:cardCornerRadius="5dp"
            app:cardElevation="5dp"
            app:cardUseCompatPadding="true"
            >

            <RelativeLayout
                android:id="@+id/parent_layout"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="10dp"
                >

                <com.devlomi.record_view.RecordView
                    android:id="@+id/record_view"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_toStartOf="@id/record_button"
                    app:slide_to_cancel_arrow="@drawable/ic_keyboard_arrow_left"
                    app:slide_to_cancel_text="Slide To Cancel"
                    app:slide_to_cancel_margin_right="10dp"/>

                <com.devlomi.record_view.RecordButton
                    android:id="@+id/record_button"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentEnd="true"
                    android:background="@drawable/bg_mic"
                    android:scaleType="centerInside"
                    app:src="@drawable/ic_mic_white"
                    />

            </RelativeLayout>

        </android.support.v7.widget.CardView>`

When ever I click button, it is canceling suddenly. That mic is not getting bigger like in sample app. What could be the reason for this issue?

**Comment by 3llomi** [comment]
@PemmasaniRajesh for the Cancel issue i assume that you are using a Small Screen Device and for that you have to **Reduce** the **Cancel Bounds**  using `recordView.setCancelBounds(someValue);` the default is **130**

and the mic is not animating properly because it's **MUST BE** in the **RootLayout**,and the Root Layout should has `match_parent`  for **height** and **width**

**Comment by 3llomi** [comment]
**UPDATE:** for the **Clipping issue**  you can set `android:clipChildren="false"` and `android:clipToPadding="false"` to your **RootLayout** ,in your case it's the `RelativeLayout`

**Comment by PemmasaniRajesh** [comment]
Thank you very much
