### ISSUE TITLE
can i build your library with 23.4.0?

### ISSUE THREAD

**Issue by rohitgarg29** [3llomi/RecordView#32]
Hi 

I have whole projects on basis of 23.4.0, when i am replacing it with 27.1.1 it gives me error regarding the layout_behavior already defined in build folders so that error is very to resolve if there is someway to integrate without 27.1.1, please let me know.

**Comment by 3llomi** [comment]
i don't know what's the problem in your project, but anyway you can clone the repo then import it to your project then modify the version  to `23.4.0`
