### ISSUE TITLE
When you finish recording, the record button disappears.

### ISSUE THREAD

**Issue by hugothomaz** [3llomi/RecordView#34]
If you click the record button and release immediately or even if you hold and aggravation is successful the button disappears. If I drag to the side and cancel the recording it does not disappear.

`<com.devlomi.record_view.RecordButton
                    android:id="@+id/recordButton"
                    android:layout_width="30dp"
                    android:layout_height="30dp"
                    android:layout_alignParentRight="true"
                    android:layout_alignParentBottom="true"
                    android:layout_gravity="center_vertical|right"
                    android:layout_marginTop="5dp"
                    android:layout_marginEnd="16dp"
                    android:layout_marginBottom="5dp"
                    android:elevation="1dp"
                    android:minWidth="44dp"
                    android:minHeight="44dp"
                    android:scaleType="fitCenter"
                    android:src="@drawable/microphone"
                    android:visibility="visible"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />`

**Comment by 3llomi** [comment]
please try the Demo Project, it's probably that there is something in your code.
