### ISSUE TITLE
AnimationHelper - NullPointerException

### ISSUE THREAD

**Issue by iskugor** [3llomi/RecordView#37]
Hello. I noticed one crash in crash logs:

`
java.lang.NullPointerException: 
  at com.devlomi.record_view.AnimationHelper.clearAlphaAnimation (AnimationHelper.java:170)
  at com.devlomi.record_view.RecordView.onActionUp (RecordView.java:312)
  at com.devlomi.record_view.RecordButton.onTouch (RecordButton.java:113)
`

No sure how it happens, I cannot reproduce it.

**Comment by 3llomi** [comment]
Hi, @iskugor , can you give more details about the issue please?

**Comment by iskugor** [comment]
@3llomi unfortunately, I cannot reproduce it, so I'm not sure what more details can I give you?

I extend "RecordView" and "RecordButton", in class that extends "RecordButton" I override "onTouch" method, maybe it's related to that?

**Comment by 3llomi** [comment]
Yes i think that causes this issue, because `RecordButton` implements `onTouch`.
can you try to **not** implement `onTouch` and report back?

**Comment by iskugor** [comment]
The problem is I need to disable touch event in some cases (similar to Whatsapp, you can send message and record audio).
And I cannot test it locally as I cannot reproduce it.

Maybe there's other way to disable recording?

**Comment by 3llomi** [comment]
Yes of course!.

first of all disable the touch movement by using
`recordButton.setListenForRecord(false);`

then you can add a listener for the record button clicks using
```java
recordButton.setOnRecordClickListener(new OnRecordClickListener() {
            @Override
            public void onClick(View v) {
                Log.d("RecordButton","RECORD BUTTON CLICKED");
            }
        });
```

**Comment by iskugor** [comment]
Thanks, I'll give it a try!

**Comment by mwshubham** [comment]
![image](https://user-images.githubusercontent.com/29930308/150310463-ad22bf42-fb7f-4275-b30d-d7f0a21fa850.png)


Is it fixed in the latest version?
WE are currently using an older version

`com.devlomi.record-view:record-view:2.0.1`
