### ISSUE TITLE
onstart

### ISSUE THREAD

**Issue by hsmedinar** [3llomi/RecordView#38]
I will try to setup recordview, but always call on start in the init, so, I will try to make gone a textview while is recording, and go back to show when finish, so I put inside onstart() text gone and in onfinish() text visible, but onstart is always called when init the activity, so my text always is gone when start activity

**Comment by 3llomi** [comment]
please try the Demo Project, it's probably that there is something in your code.

**Comment by 3llomi** [comment]
closed for non-response
