### ISSUE TITLE
Change image icon

### ISSUE THREAD

**Issue by ezeeeze** [3llomi/RecordView#40]
I am using the recordButton.setListenForRecord(false); for switch my button to click and send a text message But I cant change the icon image.
How I can change the icon using setImageIcon ???

**Comment by 3llomi** [comment]
you can change the icon just like any Normal button using `button.setImageResource`

**Comment by ezeeeze** [comment]
> you can change the icon just like any Normal button using `button.setImageResource`

Thanks!!!! I was using setImageIcon  hahah. 
Now with setImageResource run excellent!!!!!!
