### ISSUE TITLE
Basket image color.

### ISSUE THREAD

**Issue by emaanuelsilvaa** [3llomi/RecordView#42]
Hello, there is a possibility of change basket color ?

**Comment by 3llomi** [comment]
Hi, @emaanuelsilvaa!.
currently it's not implemented (i don't know why 😅), i will try to add it in a future release.

currently what you can do is adding the library to your project manually then go to `RecordView` class and add this line after initializing the views
```java
basketImg.setColorFilter(Color.BLUE);
```

**Comment by emaanuelsilvaa** [comment]
> Hi, @emaanuelsilvaa!.
> currently it's not implemented (i don't know why 😅), i will try to add it in a future release.
> 
> currently what you can do is adding the library to your project manually then go to `RecordView` class and add this line after initializing the views
> 
> ```java
> basketImg.setColorFilter(Color.BLUE);
> ```
okay thanks 😄

**Comment by juanLovera** [comment]
Another way to do this without having to manually add the library is:
recordView.findViewById<ImageView>(R.id.basket_img).setColorFilter(Color.BLUE)
