### ISSUE TITLE
Not plying on web

### ISSUE THREAD

**Issue by mohammadaliahmed** [3llomi/RecordView#43]
http://medipanda.pk/voice_storage/1576499983183r3fa35746d54b8a20.mp3 this is the recorded url.. its not working in web, but plays in app.. dont understand if there any codec issue or what

**Comment by 3llomi** [comment]
Hi, @mohammadaliahmed .
`RecordView` does NOT handle 'Audio Recording' you should handle it by using `MediaRecorder` for example.
