### ISSUE TITLE
Listview and record view

### ISSUE THREAD

**Issue by marwensniper** [3llomi/RecordView#47]
Hi,
I have a problem when i add the record view to my layout,  when i scroll in listview lthe item of list show on the tablayout
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/tPasInfoOrganisation"
        android:layout_width="311dp"
        android:layout_height="69dp"
        android:text="On dirait que vous n'avez pas des tâches à faire aujourd'hui."
        android:textAlignment="center"
        android:textColor="#000000"
        android:textSize="18sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tabsOrganisationDetail"
        app:layout_constraintVertical_bias="0.556" />

    <ImageView
        android:id="@+id/imageView9"
        android:layout_width="0dp"
        android:layout_height="90dp"
        android:scaleType="fitXY"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:srcCompat="@drawable/topbackground"></ImageView>

    <ImageView
        android:id="@+id/b_call_organisation"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="25dp"
        android:layout_marginEnd="8dp"
        android:scaleType="centerInside"
        android:src="@drawable/ic_call"
        android:tint="@android:color/white"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/lCommercialOrganisation"
        android:layout_width="0dp"
        android:layout_height="24dp"
        android:layout_marginStart="4dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="16dp"
        android:text="Commercial"
        android:textColor="@android:color/black"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toEndOf="@+id/imageView12Organisation"
        app:layout_constraintTop_toBottomOf="@+id/tTitreOrganisation" />

    <ImageView
        android:id="@+id/imageView12Organisation"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginTop="4dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tTitreOrganisation"
        app:srcCompat="@drawable/ic_users" />

    <TextView
        android:id="@+id/tTitreOrganisation"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginTop="95dp"
        android:layout_marginEnd="16dp"
        android:text="Titre de l'organistion"
        android:textColor="@android:color/black"
        android:textSize="18sp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.tabs.TabLayout
        android:id="@+id/tabsOrganisationDetail"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:layout_gravity="bottom"
        android:layout_marginTop="8dp"
        android:visibility="visible"
        android:background="#00FFFFFF"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="1.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/lCommercialOrganisation"
        app:tabIndicatorColor="@android:color/holo_red_dark"
        app:tabMode="fixed"
        app:tabTextAppearance="@style/MineCustomTabText">

        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Timeline" />

        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Détails" />

        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Offres" />

        <com.google.android.material.tabs.TabItem
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Contacts" />
    </com.google.android.material.tabs.TabLayout>

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/listviewtimelineOrganisation"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="8dp"
        android:layout_marginBottom="8dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tabsOrganisationDetail"
        android:visibility="gone"/>

    <ListView
        android:id="@+id/list_detail_organisation"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginStart="2dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="2dp"
        android:layout_marginBottom="8dp"
        android:divider="@null"
        android:dividerHeight="0dp"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tabsOrganisationDetail"></ListView>

    <ListView
        android:id="@+id/list_organisation_offre"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginStart="2dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="2dp"
        android:layout_marginBottom="8dp"
        android:divider="@null"
        android:dividerHeight="0dp"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tabsOrganisationDetail"></ListView>

    <ListView
        android:id="@+id/list_organisation_contact"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginStart="2dp"
        android:layout_marginTop="4dp"
        android:layout_marginEnd="2dp"
        android:layout_marginBottom="8dp"
        android:divider="@null"
        android:dividerHeight="0dp"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tabsOrganisationDetail"></ListView>
    <ProgressBar
        android:id="@+id/progressBarTimelineOrganisation"
        style="?android:attr/progressBarStyle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        android:layout_marginBottom="8dp"
        android:indeterminateDrawable="@drawable/progressmain"
        android:visibility="visible"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/textView10"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginTop="25dp"
        android:text="Organisation détail"
        android:textColor="#FFFFFF"
        android:textSize="18sp"
        android:textStyle="bold"
        app:layout_constraintStart_toStartOf="@+id/imageView9"
        app:layout_constraintTop_toTopOf="@+id/imageView9" />

    <com.github.clans.fab.FloatingActionMenu
        android:id="@+id/optionOrganisationMenu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:layout_marginLeft="11dp"
        android:layout_marginRight="11dp"
        android:layout_marginBottom="11dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:menu_animationDelayPerItem="55"
        app:menu_backgroundColor="@android:color/transparent"
        app:menu_buttonSpacing="0dp"
        app:menu_colorNormal="@color/colorPrimary"
        app:menu_colorPressed="@color/colorDealPerdue"
        app:menu_colorRipple="#99d4d4d4"
        app:menu_fab_size="normal"
        app:menu_icon="@drawable/fab_add"
        app:menu_labels_colorNormal="#333"
        app:menu_labels_colorPressed="#444"
        app:menu_labels_colorRipple="#66efecec"
        app:menu_labels_cornerRadius="3dp"
        app:menu_labels_ellipsize="none"
        app:menu_labels_hideAnimation="@anim/fab_slide_out_to_right"
        app:menu_labels_margin="0dp"
        app:menu_labels_maxLines="-1"
        app:menu_labels_padding="8dp"
        app:menu_labels_position="left"
        app:menu_labels_showAnimation="@anim/fab_slide_in_from_right"
        app:menu_labels_showShadow="true"
        app:menu_labels_singleLine="false"
        app:menu_labels_textColor="#f2f1f1"
        app:menu_labels_textSize="15sp"
        app:menu_openDirection="up"
        app:menu_shadowColor="#FFFFFF"
        app:menu_shadowRadius="4dp"
        app:menu_shadowXOffset="1dp"
        app:menu_shadowYOffset="4dp"
        app:menu_showShadow="true"
        tools:ignore="MissingConstraints">

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/bOptionAddNoteOrganisation"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_note_add_24px"
            app:fab_colorNormal="#FFFFFF"
            app:fab_label="Ajouter une note"
            app:fab_size="mini" />

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/bOptionAddAudioOrganisation"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_mic_24px"
            app:iconTint="@android:color/white"
            app:fab_colorNormal="#FFFFFF"
            app:fab_label="Enregistrement vocal"
            app:fab_size="mini" />

        <com.github.clans.fab.FloatingActionButton
            android:id="@+id/bOptionAddFichierOrganisation"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/ic_cloud_upload_24px"
            app:iconTint="@android:color/white"
            app:fab_colorNormal="#FFFFFF"
            app:fab_label="Télécharger un fichier"
            app:fab_size="mini" />
    </com.github.clans.fab.FloatingActionMenu>

    <com.devlomi.record_view.RecordButton
        android:id="@+id/record_button_organisation"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:layout_marginEnd="8dp"
        android:layout_marginBottom="8dp"
        android:background="@drawable/recv_bg_mic"
        android:scaleType="centerInside"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:mic_icon="@drawable/recv_ic_mic_white" />

    <com.devlomi.record_view.RecordView
        android:id="@+id/record_view_organisation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        app:counter_time_color="#ff0000"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:slide_to_cancel_arrow="@drawable/recv_ic_arrow"
        app:slide_to_cancel_arrow_color="#000000"
        app:slide_to_cancel_bounds="8dp"
        app:slide_to_cancel_margin_right="10dp"
        app:slide_to_cancel_text="Slide To Cancel" />

</androidx.constraintlayout.widget.ConstraintLayout>
```
and this is a screen of the problem : 

![Screenshot_20200414_124934_comunik com comuniksaleslite](https://user-images.githubusercontent.com/10588450/79326822-67bc8f80-7f0b-11ea-8750-09f72f6fe193.jpg)

**Comment by marwensniper** [comment]
This what happen when i scroll :

![Screenshot_20200414_124939_comunik com comuniksaleslite](https://user-images.githubusercontent.com/10588450/79326871-77d46f00-7f0b-11ea-89b5-9339547274d5.jpg)

**Comment by 3llomi** [comment]
Hey @marwensniper, that's weird!. can you send me a demo project to investigate into it?

**Comment by marwensniper** [comment]
hi @3llomi hope you are well, i can"t send you the apk because you should authentificate with account of client sorry. if you need any other explain i'm here.

**Comment by 3llomi** [comment]
i don't need your APK neither this exact project, i just need a 'Sample Project' that demonstrates this issue that you have.
you can create a new dummy project and implement a similar Setup to your project,  just to demonstrate the issue.

**Comment by marwensniper** [comment]
Finaly, i found a solution : 

i create 2 constraintlayout first have android:elevation="2dp"
 and the second i add elevation to item with 16dp, and it work :D

This is my new layout :

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:elevation="2dp">
        <Button
            android:id="@+id/bWonDeal"
            android:layout_width="88dp"
            android:layout_height="30dp"
            android:layout_marginTop="8dp"
            android:layout_marginEnd="8dp"
            android:text="Conclue"
            android:textColor="@color/colorAccent"
            android:textSize="8sp"
            app:backgroundTint="@color/colorDealDone"
            app:layout_constraintEnd_toStartOf="@+id/bLostDeal"
            app:layout_constraintTop_toBottomOf="@+id/DealDone" />
        <Button
            android:id="@+id/bLostDeal"
            android:layout_width="88dp"
            android:layout_height="30dp"
            android:layout_marginTop="8dp"
            android:layout_marginEnd="8dp"
            android:text="Perdue"
            android:textColor="@color/colorAccent"
            android:textSize="8sp"
            app:backgroundTint="@color/colorDealPerdue"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/DealDone" />
        <ImageView
            android:id="@+id/imageView9"
            android:layout_width="0dp"
            android:layout_height="90dp"
            android:scaleType="fitXY"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/topbackground"></ImageView>
        <ImageView
            android:id="@+id/iconDealEtat"
            android:layout_width="32dp"
            android:layout_height="32dp"
            android:layout_alignParentTop="true"
            android:layout_alignParentBottom="true"
            android:layout_marginTop="23dp"
            android:layout_marginEnd="16dp"
            android:contentDescription="TODO"
            android:scaleType="centerInside"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/ic_home_black_24dp" />
        <ImageView
            android:id="@+id/imageView12"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginTop="4dp"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tTitreOffre"
            app:srcCompat="@drawable/ic_users" />
        <ListView
            android:id="@+id/list_detail_offre"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_marginStart="2dp"
            android:layout_marginTop="4dp"
            android:layout_marginEnd="2dp"
            android:layout_marginBottom="8dp"
            android:divider="@null"
            android:dividerHeight="0dp"
            android:visibility="visible"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tabsDealDetail"></ListView>
        <ProgressBar
            android:id="@+id/progressBarTimeline"
            style="?android:attr/progressBarStyle"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="8dp"
            android:layout_marginTop="8dp"
            android:layout_marginEnd="8dp"
            android:layout_marginBottom="8dp"
            android:indeterminateDrawable="@drawable/progressmain"
            android:visibility="visible"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.501"
            app:layout_constraintStart_toStartOf="@+id/DealDone"
            app:layout_constraintTop_toTopOf="parent" />
        <RelativeLayout
            android:id="@+id/DealDone"
            android:layout_width="416dp"
            android:layout_height="36dp"
            android:layout_marginTop="35dp"
            android:background="#e3f9ec"
            android:visibility="visible"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tTitreOffre">
            <TextView
                android:id="@+id/lEtapeCycle"
                android:layout_width="307dp"
                android:layout_height="23dp"
                android:layout_alignParentStart="true"
                android:layout_alignParentTop="true"
                android:layout_alignParentEnd="true"
                android:layout_marginStart="50dp"
                android:layout_marginTop="6dp"
                android:layout_marginEnd="58dp"
                android:text="Etape de cycle de vente"
                android:textAlignment="center"
                android:textColor="@android:color/black"
                android:textStyle="bold" />
        </RelativeLayout>
        <TextView
            android:id="@+id/textView10"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginTop="25dp"
            android:text="Opportunité détail"
            android:textColor="#FFFFFF"
            android:textSize="18sp"
            android:textStyle="bold"
            app:layout_constraintStart_toStartOf="@+id/imageView9"
            app:layout_constraintTop_toTopOf="@+id/imageView9" />
        <TextView
            android:id="@+id/lCommercialOffre"
            android:layout_width="265dp"
            android:layout_height="24dp"
            android:layout_marginStart="4dp"
            android:layout_marginTop="4dp"
            android:text="Commercial"
            android:textColor="@android:color/black"
            app:layout_constraintStart_toEndOf="@+id/imageView12"
            app:layout_constraintTop_toBottomOf="@+id/tTitreOffre" />
        <TextView
            android:id="@+id/tTitreOffre"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginTop="95dp"
            android:layout_marginEnd="16dp"
            android:text="Titre de l'opportunité"
            android:textColor="@android:color/black"
            android:textSize="18sp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.0"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
        <TextView
            android:id="@+id/tMontantDeal"
            android:layout_width="189dp"
            android:layout_height="26dp"
            android:layout_marginStart="16dp"
            android:layout_marginTop="8dp"
            android:text="2000 $"
            android:textColor="@android:color/black"
            android:textSize="18sp"
            android:textStyle="bold"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/DealDone" />
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/listviewtimeline"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_marginStart="8dp"
            android:layout_marginTop="4dp"
            android:layout_marginEnd="8dp"
            android:layout_marginBottom="8dp"
            android:visibility="visible"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tabsDealDetail" />
        <com.github.clans.fab.FloatingActionMenu
            android:id="@+id/optionDealMenu"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_alignParentBottom="true"
            android:layout_marginLeft="11dp"
            android:layout_marginRight="11dp"
            android:layout_marginBottom="11dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:menu_animationDelayPerItem="55"
            app:menu_backgroundColor="@android:color/transparent"
            app:menu_buttonSpacing="0dp"
            app:menu_colorNormal="@color/colorPrimary"
            app:menu_colorPressed="@color/colorDealPerdue"
            app:menu_colorRipple="#99d4d4d4"
            app:menu_fab_size="normal"
            app:menu_icon="@drawable/fab_add"
            app:menu_labels_colorNormal="#333"
            app:menu_labels_colorPressed="#444"
            app:menu_labels_colorRipple="#66efecec"
            app:menu_labels_cornerRadius="3dp"
            app:menu_labels_ellipsize="none"
            app:menu_labels_hideAnimation="@anim/fab_slide_out_to_right"
            app:menu_labels_margin="0dp"
            app:menu_labels_maxLines="-1"
            app:menu_labels_padding="8dp"
            app:menu_labels_position="left"
            app:menu_labels_showAnimation="@anim/fab_slide_in_from_right"
            app:menu_labels_showShadow="true"
            app:menu_labels_singleLine="false"
            app:menu_labels_textColor="#f2f1f1"
            app:menu_labels_textSize="15sp"
            app:menu_openDirection="up"
            app:menu_shadowColor="#00FFFFFF"
            app:menu_shadowRadius="4dp"
            app:menu_shadowXOffset="1dp"
            app:menu_shadowYOffset="4dp"
            app:menu_showShadow="true"
            tools:ignore="MissingConstraints">
            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/bOptionAddNote"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_note_add_24px"
                app:fab_colorNormal="#FFFFFF"
                app:fab_label="Ajouter une note"
                app:fab_size="mini" />
            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/bOptionAddAudio"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_mic_24px"
                app:fab_colorNormal="#FFFFFF"
                app:fab_label="Enregistrement vocal"
                app:fab_size="mini"
                app:iconTint="@android:color/white" />
            <com.github.clans.fab.FloatingActionButton
                android:id="@+id/bOptionAddFichier"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_cloud_upload_24px"
                app:fab_colorNormal="#FFFFFF"
                app:fab_label="Télécharger un fichier"
                app:fab_size="mini"
                app:iconTint="@android:color/white" />
        </com.github.clans.fab.FloatingActionMenu>
        <com.google.android.material.tabs.TabLayout
            android:id="@+id/tabsDealDetail"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:layout_gravity="bottom"
            android:layout_marginTop="8dp"
            android:background="#FFFFFF"
            android:elevation="2dp"
            android:visibility="visible"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="1.0"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/bWonDeal"
            app:tabIndicatorColor="@android:color/holo_red_dark"
            app:tabMode="fixed"
            app:tabTextAppearance="@style/MineCustomTabText">
            <com.google.android.material.tabs.TabItem
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Timeline" />

            <com.google.android.material.tabs.TabItem
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Détails" />
        </com.google.android.material.tabs.TabLayout>
    </androidx.constraintlayout.widget.ConstraintLayout>
    <com.devlomi.record_view.RecordButton
        android:id="@+id/record_button_deal"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:layout_marginEnd="8dp"
        android:layout_marginBottom="8dp"
        android:background="@drawable/recv_bg_mic"
        android:scaleType="centerInside"
        android:visibility="gone"
        android:elevation="16dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:mic_icon="@drawable/recv_ic_mic_white" />
    <com.devlomi.record_view.RecordView
        android:id="@+id/record_view_deal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:elevation="16dp"
        app:counter_time_color="#ff0000"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:slide_to_cancel_arrow="@drawable/recv_ic_arrow"
        app:slide_to_cancel_arrow_color="#000000"
        app:slide_to_cancel_bounds="8dp"
        app:slide_to_cancel_margin_right="10dp"
        app:slide_to_cancel_text="Slide To Cancel" />
</androidx.constraintlayout.widget.ConstraintLayout>
