### ISSUE TITLE
Pull Request declined

### ISSUE THREAD

**Issue by Andreu35** [3llomi/RecordView#48]
Hi, I cloned this repository because I like this library and I refactored to Kotlin all the code to help but, I can't push the code because I don't have permissions.
Please, can you give me permissions to push the Kotlin code?

Thank you very much ;)
-Andreu35.

**Comment by 3llomi** [comment]
Hey @Andreu35, Thanks for your contribution, basically you have to `fork` this Library to your Github account, and **then** you can `clone` it from your account and start adding your code/refactoring. once everything is ready you can commit and push it to your repository, lastly you can submit a Pull request so i can review it and approve it.

let me know if you need any help.
