### ISSUE TITLE
Doesn't work well in BottomSheetDialogFragment

### ISSUE THREAD

**Issue by JobGetabu** [3llomi/RecordView#49]
When added to a BottomSheetDialogFragment view
Once clicked does not detect click end gesture

**Comment by 3llomi** [comment]
Hey @JobGetabu,
probably because touchEvents intercepting with each other, can you try to apply the same idea as here #17 ?

**Comment by JobGetabu** [comment]
Tried different ways & touchEvents 
But the slide to Cancel gesture fails

**Comment by 3llomi** [comment]
can you send me a sample project so I can take a look?

**Comment by 3llomi** [comment]
after some testing i've noticed that touches events intercepts with each other.
what i am thinking of is to use `BottomSheetBehavior` and `setDraggable` to false when recording.
for example in onStart `setDraggable` to false, and on Finish set it back to true.

feel free to re-open this issue if it didn't work.
