### ISSUE TITLE
Button is not working in api level 24 (android version 7.0+)

### ISSUE THREAD

**Issue by shahzi8285** [3llomi/RecordView#5]
I am developing a chatting app and using your wonderful library..But button is not proprerly working in android version 7+ it has to tap continuesly 2-3times..Please help

**Comment by 3llomi** [comment]
@shahzi8285 could you please provide more info about the problem ?
are the Callbacks working or not?

**Comment by shahzi8285** [comment]
`
           recordButton.setOnRecordClickListener(new OnRecordClickListener() {
                  @Override
                   public void onClick(View v) {
                   if(!recordButton.isListenForRecord()){
                             i = i+1;
                           count.setText("Count" + Integer.toString(i));
                     }
                    }
                      });

        editText.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {

            }

            @Override
            public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
                if(charSequence.length() !=0){
                    recordButton.setListenForRecord(false);
                }else{
                    recordButton.setListenForRecord(true);
                }
            }

            @Override
            public void afterTextChanged(Editable editable) {

            }
        });`



it is taking around 5-6 taps to click once..and this problem is occuring in android 7+ only


kindly solve this

**Comment by shahzi8285** [comment]
Is there any help?

**Comment by 3llomi** [comment]
please try it on a Real Device instead of **Emulator** . the `OnRecordClickListener` will **ONLY** works if the click input wasn't moved

**Comment by 3llomi** [comment]
@shahzi8285 a new update has been pushed and hopefully the problem solved
please feel free to reopen this issue if you encountered any issues
