### ISSUE TITLE
use in fragment

### ISSUE THREAD

**Issue by plokijuhyg** [3llomi/RecordView#51]
hi for use in fragment what do i do ?
my error if use in fragment :

E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.devlomi.record_view.RecordView.onActionDown(com.devlomi.record_view.RecordButton, android.view.MotionEvent)' on a null object reference
        at com.devlomi.record_view.RecordButton.onTouch(RecordButton.java:104)

**Comment by 3llomi** [comment]
Hey @plokijuhyg , Sorry for late reply.
can you reproduce it? i've just tested it on a Fragment and it works good.
