### ISSUE TITLE
Restore RecordButton view from active recording after user has dragged touch outside

### ISSUE THREAD

**Issue by ZaifSenpai** [3llomi/RecordView#53]
Button is still showing Recording when user's pointer has left the view by dragging to other side.
See video for reference:
[Video](https://youtu.be/uo8YCajY-xk)

**Comment by cett01** [comment]
Yeap, Yeah I'm facing the same problem, on the scrollview.

**Comment by 3llomi** [comment]
Hi @ZaifSenpai , i can see from the video that you're using it inside a ScrollView/RecyclerView.
can you try solution implemented here #17   and report back?
