### ISSUE TITLE
Record button and media player.

### ISSUE THREAD

**Issue by VirajShirwalkar** [3llomi/RecordView#57]
Hi, i have noticed that the record button gets bigger while recording or button pressed and there is no such method to change  or enable-disable record button animation.
Secondly, if there is no recording happened via library then media player contents should be removed. It is not getting used and library size can be reduced.
Delete animated icon has no color change available.
If possible, please provide some customization.
Thanks.

**Comment by 3llomi** [comment]
Hi, 

> have noticed that the record button gets bigger while recording or button pressed and there is no such method to change or enable-disable record button animation.

i didn't implement that.

> Secondly, if there is no recording happened via library then media player contents should be removed. It is not getting used and library size can be reduced

there is **NO** recording mechanism implemented in this lib, so you have the freedom to implement whatever you like. like MediaRecorder for Example.

**Comment by VirajShirwalkar** [comment]
I like the library and requesting you to please provide some customizations. Thanks.

**Comment by 3llomi** [comment]
Okay, i'll leave this issue open, maybe sometime i can add these customization.
to recap, we need to add these functionalities
1. enable or disable record animation
2. add the ability to change delete animation icon color (trash icon).

**Comment by 3llomi** [comment]
Added in V.3.0.1
