### ISSUE TITLE
Weird Scrolling with Record Button

### ISSUE THREAD

**Issue by Sarimsaljook** [3llomi/RecordView#58]
I am building a chat app and every Time i add a record button to the bottom of my recycler view it starts scrolling weird. Here is whats happening,

here is my xml for the chat activity: 
 `<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/chatting_backgrounf"
    android:theme="@style/Theme.AppCompat.Light.NoActionBar"
    tools:context=".SarimPage">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="61dp"
        android:background="#007C70"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <TextView
            android:id="@+id/displayUser"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="120dp"
            android:layout_marginLeft="120dp"
            android:layout_marginTop="10dp"
            android:autoSizeTextType="uniform"
            android:ellipsize="end"
            android:maxLines="1"
            android:text="User"
            android:textColor="#000000"
            android:textSize="20sp"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <ImageButton
            android:id="@+id/imageButton2"
            android:layout_width="39dp"
            android:layout_height="35dp"
            android:layout_marginStart="14dp"
            android:layout_marginTop="16dp"
            android:background="#007C70"
            android:clickable="true"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/abc_vector_test" />

        <de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/chat_profile_image"
            android:layout_width="67dp"
            android:layout_height="51dp"
            android:layout_marginStart="52dp"
            android:layout_marginLeft="52dp"
            android:layout_marginTop="5dp"
            android:src="@drawable/circle_cropped__4_"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <ImageButton
            android:id="@+id/imageButton3"
            android:layout_width="30dp"
            android:layout_height="27dp"
            android:layout_marginStart="320dp"
            android:layout_marginTop="20dp"
            android:background="#007C70"
            android:clickable="true"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@android:drawable/stat_sys_phone_call" />

        <TextView
            android:id="@+id/userStatus"
            android:layout_width="130dp"
            android:layout_height="23dp"
            android:layout_marginStart="120dp"
            android:layout_marginTop="35dp"
            android:text="online"
            android:textColor="#BDD3D6"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <ImageButton
            android:id="@+id/VideoCall"
            android:layout_width="31dp"
            android:layout_height="27dp"
            android:layout_marginStart="286dp"
            android:layout_marginTop="20dp"
            android:background="#007C70"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/ic_baseline_videocam_24"
            tools:ignore="VectorDrawableCompat" />

        <ImageView
            android:id="@+id/stats"
            android:layout_width="16dp"
            android:layout_height="16dp"
            android:layout_marginStart="95dp"
            android:layout_marginLeft="95dp"
            android:layout_marginTop="40dp"
            android:visibility="invisible"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/online" />

        <ImageView
            android:id="@+id/stats2"
            android:layout_width="16dp"
            android:layout_height="16dp"
            android:layout_marginStart="95dp"
            android:layout_marginLeft="95dp"
            android:layout_marginTop="40dp"
            android:visibility="invisible"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/offline" />

        <ImageView
            android:id="@+id/stats3"
            android:layout_width="16dp"
            android:layout_height="16dp"
            android:layout_marginStart="95dp"
            android:layout_marginLeft="95dp"
            android:layout_marginTop="40dp"
            android:visibility="invisible"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:srcCompat="@drawable/away" />

    </androidx.constraintlayout.widget.ConstraintLayout>

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/chat_list_view"
        android:layout_width="match_parent"
        android:layout_height="530dp"
        android:layout_marginTop="62dp"
        android:background="@drawable/chatting_backgrounf"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/goDown"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_marginStart="308dp"
        android:layout_marginLeft="308dp"
        android:layout_marginTop="520dp"
        android:clickable="true"
        android:visibility="invisible"
        app:backgroundTint="#FFFFFF"
        app:fabSize="mini"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:srcCompat="@drawable/double_down"
        tools:ignore="VectorDrawableCompat" />

    <com.devlomi.record_view.RecordView
        android:id="@+id/record_view"
        android:layout_width="295dp"
        android:layout_height="50dp"
        android:layout_alignParentBottom="true"
        android:layout_toLeftOf="@id/record_button"
        android:layout_marginTop="600dp"
        app:counter_time_color="#ff0000"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:slide_to_cancel_arrow="@drawable/recv_ic_arrow"
        app:slide_to_cancel_arrow_color="#000000"
        app:slide_to_cancel_bounds="8dp"
        app:slide_to_cancel_margin_right="10dp"
        app:slide_to_cancel_text="Slide To Cancel"
        tools:ignore="NotSibling"/>

    <com.devlomi.record_view.RecordButton
        android:id="@+id/record_button"
        android:layout_width="40dp"
        android:layout_height="43dp"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:layout_marginStart="252dp"
        android:layout_marginTop="604dp"
        android:background="@drawable/recv_bg_mic"
        android:scaleType="centerInside"
        android:src="@drawable/ic_baseline_mic_7"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <EditText
        android:id="@+id/messageInput"
        android:layout_width="243dp"
        android:layout_height="50dp"
        android:layout_marginStart="5dp"
        android:layout_marginTop="600dp"
        android:background="@drawable/rounded_edittext"
        android:drawableStart="@drawable/ic_baseline_add_photo_alternate_24"
        android:drawableEnd="@drawable/ic_baseline_mic_90"
        android:drawablePadding="10dp"
        android:ems="10"
        android:hint="@string/enter_message_here"
        android:inputType="textMultiLine"
        android:maxLength="285"
        android:padding="15dp"
        android:textColorLink="#075E54"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/floatingActionButton2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="299dp"
        android:layout_marginTop="597dp"
        android:clickable="true"
        app:backgroundTint="#17A194"
        app:fabSize="auto"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:srcCompat="@drawable/ic_baseline_send_24"
        tools:ignore="VectorDrawableCompat" />

</androidx.constraintlayout.widget.ConstraintLayout>`

here is video to usestand what is happening
https://user-images.githubusercontent.com/80625774/117446590-b5ac9700-af55-11eb-8ce0-f8de7d6d8c99.mp4

**Comment by 3llomi** [comment]
can you try the sample app? maybe there is an issue with your layout that's conflicting with RecordView?

**Comment by Sarimsaljook** [comment]
ok

**Comment by mahmoudfathy01010** [comment]
I have the same issue, If you figured any solution please tell me

**Comment by 3llomi** [comment]
can you send me a sample project that i can test against?

**Comment by Sarimsaljook** [comment]
ive tried it in a sample project it works it is the recycker view that is conficlitnv with your layout

**Comment by 3llomi** [comment]
@Sarimsaljook  can you try this #17 ?
