### ISSUE TITLE
Record Button is hidden after the record finished

### ISSUE THREAD

**Issue by DilipRipenApps** [3llomi/RecordView#60]
@Override
            public void onFinish(long recordTime) {
                String time = CommonUtils.getHumanTimeText(recordTime);
                Toast.makeText(ChatActivity.this, "Recorded Time is: " + time, Toast.LENGTH_SHORT).show();
                mediaRecorder.reset();
                mediaRecorder.release();

                binding.textMessage.setVisibility(View.VISIBLE);
                binding.recordView.setVisibility(View.GONE);
                binding.recordButton.setVisibility(View.VISIBLE);
                binding.gif.setVisibility(View.VISIBLE);
                binding.camera.setVisibility(View.VISIBLE);

                sendRecodingMessage();
            }

**Comment by 3llomi** [comment]
please checkout the Demo Project, i believe there is something wrong with your layout.
