### ISSUE TITLE
Application attributes in AndroidManifest

### ISSUE THREAD

**Issue by alexandrplusnin** [3llomi/RecordView#63]
Thank you for your great work on this project! I wonder if it makes sense to remove <application> tag from library's AndroidManifest.

https://github.com/3llomi/RecordView/blob/master/record-view/src/main/AndroidManifest.xml

I want to use RecordView in my own library but I am worried that it can lead to manifest merging conflicts (for example, if user of my library is using different attribute "android:label"). Obviously, user can overcome it by using tools:replace="android:label", but still it is an extra hiccup that can be avoided.

I don't think that there is a way for me to remove these attributes from my library. Unless I'm missing something.

What do you think about it?

**Comment by 3llomi** [comment]
Yes, you're right!. i just got rid of application tags in V 3.0.2.
