### ISSUE TITLE
recordButton.setOnRecordClickListener and recordView.setOnRecordListener don't work together?

### ISSUE THREAD

**Issue by iAmJuan550** [3llomi/RecordView#67]
Is it possible to do both?

**Comment by 3llomi** [comment]
It is possible, but not at the same time.
for example you have to have some kind of state management, like in a Chat app, if there was no Text in EditText you would **enable** `listenForRecord` so the RecordButton can handle Recording. and in case if there was a Text in EditText you would **disable** `listenForRecord` to enable clicks on RecordButton.
