### ISSUE TITLE
RuntimeException: Duplicate class  com.devlomi.record_view.AnimationHelper found in modules jetified-RecordView-3.0.2-runtime.jar

### ISSUE THREAD

**Issue by HosseinKurd** [3llomi/RecordView#68]
In version : `3.0.2` of `com.github.3llomi:RecordView:` I just faced error:

Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.devlomi.record_view.AnimationHelper found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.AnimationHelper$1 found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.AnimationHelper$2 found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.AnimationHelper$2$1 found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.AnimationHelper$3 found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.AnimationHelper$4 found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.BuildConfig found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.DpUtil found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.OnBasketAnimationEnd found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.OnRecordClickListener found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.OnRecordListener found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.RecordButton found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.RecordView found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.RecordView$1 found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)
  Duplicate class com.devlomi.record_view.ScaleAnim found in modules jetified-RecordView-3.0.2-runtime.jar (com.github.3llomi:RecordView:3.0.2) and jetified-record-view-2.0.1-runtime.jar (com.devlomi.record-view:record-view:2.0.1)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by bogdan-fesenko** [comment]
@HosseinKurd Hey!
You need to include only one of two lines at the Install step:
this:
//for AppCompat use:
//appcompat v26+ is higly recommended to support older APIs
implementation 'com.devlomi.record-view:record-view:2.0.1'or this
//for AndroidX use:
implementation 'com.github.3llomi:RecordView:3.1.1'

The error happens when you put 2 lines together
