### ISSUE TITLE
How to change record button background color?

### ISSUE THREAD

**Issue by FarooqKhattak** [3llomi/RecordView#71]
I am unable to change the backgound green type color to my custom color.

**Comment by 3llomi** [comment]
It's just a normal background, you can change it in xml using `android:background=...`
Or in code using `recordButton.setBackground..`

**Comment by 3llomi** [comment]
I used Shape Drawable as a background in the Demo, If you want the same shape, go to `record-view/drawable/recv_bg_mic.xml` and copy it to your folder, change its color and reference it in your xml.

OR simply just use background tint 
`android:backgroundTint="@color/colorBlue"`

**Comment by FarooqKhattak** [comment]
Thanks for the tip!
