### ISSUE TITLE
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.devlomi.record_view.RecordView.onActionDown(com.devlomi.record_view.RecordButton, android.view.MotionEvent)' on a null object reference

### ISSUE THREAD

**Issue by SherazAli-67** [3llomi/RecordView#74]
Hey, I have facing with this issue, I have just defined the RecordView and Record Button in the xml nothing else, and when i touch the record, application crashes.

**Comment by 3llomi** [comment]
Hi @SherazAli-67 
Can you reproduce it? Please share the Code
