### ISSUE TITLE
Not working in scrollview prperly

### ISSUE THREAD

**Issue by rajscet** [3llomi/RecordView#8]
when i drag record button from top/bottom/right , buttton is hang and after that i press again record button to get old situation of record button and recording was canaclled

**Comment by 3llomi** [comment]
@rajscet sorry for late reply.
i have tried [this ](https://stackoverflow.com/a/31425613/4130286)`Custom ScrollView` and it's working fine

**Comment by icangku** [comment]
How About NestedScrollView ?

**Comment by 3llomi** [comment]
@icangku i think you have to make same approach like [here](https://stackoverflow.com/a/31425613/4130286), but instead of extending `ScrollView` you have to extend `NestedScrollView`.

give it a shot and let me know how it goes.
