### ISSUE TITLE
just click on mic 

### ISSUE THREAD

**Issue by KarmaTechnolabs** [3llomi/RecordView#87]
just click on mic and then again try to click on mic
getting crash on    mediaRecorder.prepare();   AudioRecorder line 25

**Comment by kumarsibaprasad100** [comment]
Reinitialize MediaRecorder before mediaRecorder.prepare()
i.e: 
            mediaRecorder = new MediaRecorder();
            mediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
            mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
            mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);
            mediaRecorder.setOutputFile(filePath);
            mediaRecorder.prepare();
            mediaRecorder.start();
