### ISSUE TITLE
UI allignment issue and swipe to cancel not working properly

### ISSUE THREAD

**Issue by GobinathKPerumal** [3llomi/RecordView#90]
Hi @3llomi , @sdarvish 

we are using your lib for recording audio - "'com.github.3llomi:RecordView:3.1.3'", we facing some UI issues in your library, here I shared the step to reproduce that issue and screen recording also kindly find and fix it.

Steps to reproduce:
1. Hold the mic button for 2 to 3 secs to start recording.
2. Then try to swipe the button left side, for canceling the recording, swipe to cancel not working.
3. Then manually cancel the record, while clicking the mic button, after the UI is rearranged.

Screen recording
https://user-images.githubusercontent.com/109264156/227881609-3d127dd1-7184-49ae-8fa0-9e8a43b87285.mp4

**Comment by 3llomi** [comment]
Hey @GobinathKPerumal ,
I can see that you're adding RecordView inside a RecyclerView, please implement the solution mentioned here #17
