### ISSUE TITLE
Plugin crashes when quickly tapping on the record button [Very rare]

### ISSUE THREAD

**Issue by shahimclt** [3llomi/RecordView#93]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.view.animation.Animation.cancel()' on a null object reference
com.devlomi.record_view.AnimationHelper.clearAlphaAnimation (AnimationHelper.java:181)
com.devlomi.record_view.RecordView.resetRecord (RecordView.java:558)
com.devlomi.record_view.RecordView.finishAndSaveRecord (RecordView.java:516)
com.devlomi.record_view.RecordView.onActionUp (RecordView.java:485)
com.devlomi.record_view.RecordButton.onTouch (RecordButton.java:125)
android.view.View.dispatchTouchEvent (View.java:14348)

**Comment by 3llomi** [comment]
#91
