### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by Romady03** [3llomi/RecordView#95]
Hello, I have the animations but nothing is displayed on my chat but is recorded well

**Comment by 3llomi** [comment]
Hi @Romady03 ,
Can you try out the sample and report back?

**Comment by Romady03** [comment]
Good morning,
I have it set up fine but I would like it to display on my chat for the recipient.
THANKS

**Comment by 3llomi** [comment]
Please note that this library is to record voice only. You have to implement the chat mechanism on your own.
